### ISSUE TITLE
Secure connection not working

### ISSUE THREAD

**Issue by sebakerckhof** [camunda-community-hub/zeebe-client-node-js#219]
I'm trying to connect to a secure zeebe gateway. I secured it with a self-signed certificate for which the CA is in my trust store and I also pass it via the commonSSL options. If I disable security in the gateway it works.
It also works via zbctl with security on and with the same ca chain file.

Note that this is not the same issue as https://github.com/camunda-community-hub/zeebe-client-node-js/issues/218 , since in my case the handshake does work, but the grpc write after the handshake seems to fail

## Expected Behavior
It should work the same as with non-secure connection.

## Current Behavior
The handshake works, but after that, I get:
```
{ Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/home/seba/dev/ebo/tests/zeebe/zeebe-message-correlation/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/seba/dev/ebo/tests/zeebe/zeebe-message-correlation/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/seba/dev/ebo/tests/zeebe/zeebe-message-correlation/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/seba/dev/ebo/tests/zeebe/zeebe-message-correlation/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/seba/dev/ebo/tests/zeebe/zeebe-message-correlation/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 2,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'Stream removed' }
```

## Steps to Reproduce
1. Run a secured zeebe gateway with a self-signed cert
2. Try to publish a message with zeebe-node, give the ca chain via the customSSL option and set useTLS to true

## Context (Environment)
I'm using both zeebe and zeebe-node 0.26.0.

Works with zbctl

**Comment by jwulf** [comment]
Users are using version 8.2.x with self-signed certificates, so I think this is fixed now. 

Please reopen if the error persists with newer versions.
